kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "openIM.fullname" . }}
  labels:
    {{- include "openIM.labels" . | nindent 4 }}
data:
  config.yaml: |
    # The class cannot be named by Pascal or camel case.
    # If it is not used, the corresponding structure will not be set,
    # and it will not be read naturally.
    serverversion: 2.3.7
    #---------------Infrastructure configuration---------------------#
    zookeeper:
      schema: openim
      #单机部署时，默认即可
      zkAddr:
      {{- range .Values.configmap.zookeeper.zkAddr }}
      - {{ . }}
      {{- end }}
      userName: {{.Values.configmap.zookeeper.userName}}
      password: {{.Values.configmap.zookeeper.password}}
    mysql:
      #mysql地址 目前仅支持单机，默认即可
      dbMysqlAddress:
      {{- range .Values.configmap.mysql.dbMysqlAddress }}
      - {{ . }}
      {{- end }}
      dbMysqlUserName: {{.Values.configmap.mysql.dbMysqlUserName}} #mysql用户名，建议修改
      dbMysqlPassword: {{.Values.configmap.mysql.dbMysqlPassword}} # mysql密码，建议修改
      dbMysqlDatabaseName: {{.Values.configmap.mysql.dbMysqlDatabaseName | default "openIM_v2" }} #默认即可
      dbTableName: eMsg #默认即可
      dbMsgTableNum: 1
      dbMaxOpenConns: 100
      dbMaxIdleConns: 10
      dbMaxLifeTime: 5
      logLevel: 4 #1=slient 2=error 3=warn 4=info
      slowThreshold: 500

    mongo:
      dbUri: ""#当dbUri值不为空则直接使用该值
      #单机时为mongo地址，使用分片集群时，为mongos地址 默认即可
      dbAddress:
      {{- range .Values.configmap.mongo.dbAddress }}
      - {{ . }}
      {{- end }}
      dbDirect: false
      dbTimeout: 60
      dbDatabase: {{.Values.configmap.mongo.dbDatabase | default "openIM" }}  #mongo db 默认即可
      dbSource: {{.Values.configmap.mongo.dbSource | default "admin" }}
      dbUserName: {{.Values.configmap.mongo.dbUserName}} #mongo用户名，建议先不设置
      dbPassword: {{.Values.configmap.mongo.dbPassword}}  #mongo密码，建议先不设置
      dbMaxPoolSize: 100
      dbRetainChatRecords: 3650 #mongo保存离线消息时间（天），根据需求修改
      chatRecordsClearTime: "0 2 * * 3" # 每周三凌晨2点清除消息，该配置和linux定时任务一样， 清理操作建议设置在用户活跃少的时候 # 0 3 * * *

    redis:
      dbAddress:
      {{- range .Values.configmap.redis.dbAddress }}
      - {{ . }}
      {{- end }}
      dbMaxIdle: 128
      dbMaxActive: 0
      dbIdleTimeout: 120
      dbUserName: {{.Values.configmap.redis.dbUserName}}
      dbPassWord: {{.Values.configmap.redis.dbPassWord}} #redis密码 建议修改
      enableCluster: {{.Values.configmap.redis.enableCluster}} #如果外部redis以集群方式启动，需要打开此开关

    kafka:
      SASLUserName: {{.Values.configmap.kafka.SASLUserName}}
      SASLPassword: {{.Values.configmap.kafka.SASLPassword}}
      ws2mschat:
        addr:
        {{- range .Values.configmap.kafka.ws2mschat.addr }}
        - {{ . }}
        {{- end }}
        topic: {{.Values.configmap.kafka.ws2mschat.topic | default "ws2ms_chat"}} #用于mongo和mysql保存消息
      msgtomongo:
        addr:
        {{- range .Values.configmap.kafka.msgtomongo.addr }}
          - {{ . }}
        {{- end }}
        topic: {{.Values.configmap.kafka.msgtomongo.topic | default "msg_to_mongo"}}
      ms2pschat:
        addr:
        {{- range .Values.configmap.kafka.ms2pschat.addr }}
          - {{ . }}
        {{- end }}
        topic: {{.Values.configmap.kafka.ms2pschat.topic | default "ms2ps_chat"}}
      msgtomodify:
        addr:
        {{- range .Values.configmap.kafka.msgtomodify.addr }}
          - {{ . }}
        {{- end }}
        topic: {{.Values.configmap.kafka.msgtomodify.topic | default "msg_to_modify"}}
      consumergroupid:
        msgToTransfer: mongo
        msgToMongo: mongo_ex
        msgToMySql: mysql
        msgToPush: push
        msgToModify: modify


    #---------------Internal service configuration---------------------#

    # The service ip default is empty,
    # automatically obtain the machine's valid network card ip as the service ip,
    # otherwise the configuration ip is preferred
    #如果是单机模式，用0.0.0.0或者不填，默认即可

    #作为rpc时，注册到etcd的地址，单机默认即可，如果是集群部署，需要修改（具体使用内网地址还是外网地址，要依情况而定，目的是api/gateway能访问到）
    rpcRegisterIP:
    #默认即可
    listenIP: 0.0.0.0


    api:
      openImApiPort: [ 10002 ] #api服务端口，默认即可，需要开放此端口或做nginx转发
      listenIP: 0.0.0.0

    #对象存储服务，以下配置二选一，目前支持两种，腾讯云和minio，二者配置好其中一种即可（如果使用minio参考https://doc.rentsoft.cn/#/qa/minio搭建minio服务器）
    credential: #腾讯cos，发送图片、视频、文件时需要，请自行申请后替换，必须修改


    object:
      enable: minio
      apiURL: http://{{include "openIM.api" . }}-{{ include "openIM.fullname" . }}.{{.Release.Namespace}}.svc.cluster.local:{{.Values.service.port}}/third/object
      minio: #MinIO 发送图片、视频、文件时需要，请自行申请后替换，必须修改。 客户端初始化InitSDK，中 object_storage参数为minio
        tempBucket: {{.Values.configmap.minio.tempBucket | default "openim"}}
        dataBucket: {{.Values.configmap.minio.dataBucket | default "openim"}}
        location: {{.Values.configmap.minio.location }}
        endpoint: http://{{ include "openIM.minioAPIURL" . | trim }}:{{ required "istio public port is required" .Values.istio.publicPort }}
        accessKeyID: {{.Values.configmap.minio.accessKeyID }}
        secretAccessKey: {{.Values.configmap.minio.secretAccessKey }}
        isDistributedMod: false # 是否分布式多硬盘部署 默认docker-compose中为false，如果是多硬盘部署，需要修改为true
      tencent:
        appID:
        region:
        bucket:
        secretID:
        secretKey:
      ali: # ali oss
        regionID:
        accessKeyID:
        accessKeySecret:
        stsEndpoint:
        ossEndpoint:
        bucket:
        finalHost:
        stsDurationSeconds:
        OssRoleArn:
      aws:
        accessKeyID:                              #AssumeRole用户关联的accessKeyID
        accessKeySecret:                          #AssumeRole用户关联的accessKeySecrect
        region:                                   #分区
        bucket:                                   #桶
        finalHost:                                #对外Host
        roleArn:                                  #RoleArn
        externalId:                               #角色扩展Id
        roleSessionName:                          #角色SESSION名称

    rpcregistername: #rpc注册服务名，默认即可
      openImUserName: User
      openImFriendName: Friend
      openImMsgName: Msg
      openImPushName: Push
      openImMessageGatewayName: MessageGateway
      openImGroupName: Group
      openImAuthName: Auth
      openImConversationName: Conversation
      openImRtcName: Rtc
      openImThirdName: Third

    log:
      storageLocation: ../logs/
      rotationTime: 24
      remainRotationCount: 2 #日志数量
      #日志级别 6表示全都打印，测试阶段建议设置为6
      remainLogLevel: 6
      isStdout: true
      isJson: false
      withStack: false

    modulename: #日志文件按模块命名，默认即可
      longConnSvrName: msg_gateway
      msgTransferName: msg_transfer
      pushName: push

    longconnsvr:
      openImWsPort: [ 10001 ] # ws服务端口，默认即可，要开放此端口或做nginx转发
      websocketMaxConnNum: 10000
      websocketMaxMsgLen: 4096
      websocketTimeOut: 10

    ## 推送只能开启一个 enable代表开启
    push:
      tpns: #腾讯推送，暂未测试 暂不要使用
        ios:
          accessID: 1600018281
          secretKey: 3cd68a77a95b89e5089a1aca523f318f
        android:
          accessID: 111
          secretKey: 111
        enable: false # true or false (bool)
      jpns: #极光推送 在极光后台申请后，修改以下四项，必须修改
        appKey:
        masterSecret:
        pushUrl:
        pushIntent:
        enable: false # true or false (bool)
      getui: #个推推送
        pushUrl: "https://restapi.getui.com/v2/$appId"
        masterSecret: ""
        appKey: ""
        intent: ""
        enable: false # true or false (bool)
        channelID: ""
        channelName: ""
      fcm: #firebase cloud message 消息推送
        serviceAccount: "openim-5c6c0-firebase-adminsdk-ppwol-8765884a78.json" #帐号文件，此处需要改修配置，并且这个文件放在 config目录下
        enable: false

    manager:
      #app管理员userID和对应的secret  建议修改。 用于管理后台登录，也可以用户管理后台对应的api
      appManagerUid: [ "openIM123456","openIM654321", "openIM333", "openIMAdmin" ]
      nickname: [ "系统通知","openIM654321", "openIM333", "openIMAdmin" ]


    secret: tuoyun
    # 多端互踢策略
    # 1：多平台登录：Android、iOS、Windows、Mac 每种平台只能一个在线，web端可以多个同时在线
    multiloginpolicy: 1

    #msg log insert to db
    chatpersistencemysql: true
    #消息缓存时间
    msgCacheTimeout: 86400
    #群聊已读开启
    groupMessageHasReadReceiptEnable: true
    #单聊已读开启
    singleMessageHasReadReceiptEnable: true

    #token config
    tokenpolicy:
      accessSecret: "OpenIM_server" #token生成相关，默认即可
      # Token effective time day as a unit
      accessExpire: 90  #token过期时间（天） 默认即可
    messageverify:
      friendVerify: false

    #ios系统推送声音以及标记计数
    iospush:
      pushSound: "xxx"
      badgeCount: true
      production: false

    callback:
      # callback url 需要自行更换callback url
      callbackUrl: "http://127.0.0.1:10008/callback/open_im"
      # 开启关闭操作前后回调的配置
      callbackBeforeSendSingleMsg:
        enable: false # 回调是否启用
        callbackTimeOut: 2 # 回调超时时间
        callbackFailedContinue: true # 回调超时是否继续执行代码
      callbackAfterSendSingleMsg:
        enable: false
        callbackTimeOut: 2
      callbackBeforeSendGroupMsg:
        enable: false
        callbackTimeOut: 2
        callbackFailedContinue: true
      callbackAfterSendGroupMsg:
        enable: false
        callbackTimeOut: 2
      callbackMsgModify:
        enable: false
        callbackTimeOut: 2
        callbackFailedContinue: true
      callbackUserOnline:
        enable: false
        callbackTimeOut: 2
      callbackUserOffline:
        enable: false
        callbackTimeOut: 2
      callbackUserKickOff:
        enable: false
        callbackTimeOut: 2
      callbackOfflinePush:
        enable: false
        callbackTimeOut: 2
        callbackFailedContinue: true # 回调超时是否继续离线推送
      callbackOnlinePush:
        enable: false
        callbackTimeOut: 2
        callbackFailedContinue: true # 回调超时是否继续离线推送
      callbackSuperGroupOnlinePush:
        enable: false
        callbackTimeOut: 2
        callbackFailedContinue: true # 回调超时是否继续离线推送
      callbackBeforeAddFriend:
        enable: false
        callbackTimeOut: 2
        callbackFailedContinue: true # 回调超时是否继续
      callbackBeforeCreateGroup:
        enable: false
        callbackTimeOut: 2
        callbackFailedContinue: true # 回调超时是否继续
      callbackBeforeMemberJoinGroup:
        enable: false
        callbackTimeOut: 2
        callbackFailedContinue: true # 回调超时是否继续
      callbackBeforeSetGroupMemberInfo:
        enable: false
        callbackTimeOut: 2
        callbackFailedContinue: true # 回调超时是否继续
      callbackSetMessageReactionExtensions:
        enable: false
        callbackTimeOut: 2
        callbackFailedContinue: true # 回调超时是否继续

    rtc:
      signalTimeout: 35

    # prometheus每个服务监听的端口数量需要和rpc port保持一致
    prometheus:
      enable: true

  notification.yaml: |
    groupCreated:
      isSendMsg: true #是否发送消息，false不发消息为无声的触发同步。true发消息需要触发会话，rpc notification直接发两次，一次消息一次通知, options字段isNotification是否为通知
      reliabilityLevel: 1 # 1为online才发送 2为必达
      unreadCount: false # 只在isSendMsg为true的情况下有作用
      offlinePush:
        enable: false # 开启该开关
        title: "create group title" # xx create the group
        desc: "create group desc"
        ext: "create group ext"

    # 不加消息contentType，content统一json 结构体使用pb的


    groupInfoSet:
      isSendMsg: false
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: false
        title: "groupInfoSet title"
        desc: "groupInfoSet desc"
        ext: "groupInfoSet ext"


    joinGroupApplication:
      isSendMsg: false
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: false
        title: "joinGroupApplication title"
        desc: "joinGroupApplication desc"
        ext: "joinGroupApplication ext"

    memberQuit:
      isSendMsg: true
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: false
        title: "memberQuit title"
        desc: "memberQuit desc"
        ext: "memberQuit ext"

    groupApplicationAccepted:
      isSendMsg: false
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: false
        title: "groupApplicationAccepted title"
        desc: "groupApplicationAccepted desc"
        ext: "groupApplicationAccepted ext"

    groupApplicationRejected:
      isSendMsg: false
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: false
        title: " title"
        desc: " desc"
        ext: " ext"


    groupOwnerTransferred:
      isSendMsg: true
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: false
        title: "groupOwnerTransferred title"
        desc: "groupOwnerTransferred desc"
        ext: "groupOwnerTransferred ext"

    memberKicked:
      isSendMsg: true
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: false
        title: "memberKicked title"
        desc: "memberKicked desc"
        ext: "memberKicked ext"

    memberInvited:
      isSendMsg: true
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: false
        title: "memberInvited title"
        desc: "memberInvited desc"
        ext: "memberInvited ext"

    memberEnter:
      isSendMsg: true
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: false
        title: "memberEnter title"
        desc: "memberEnter desc"
        ext: "memberEnter ext"

    groupDismissed:
      isSendMsg: true
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: false
        title: "groupDismissed title"
        desc: "groupDismissed desc"
        ext: "groupDismissed ext"

    groupMuted:
      isSendMsg: true
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: false
        title: "groupMuted title"
        desc: "groupMuted desc"
        ext: "groupMuted ext"

    groupCancelMuted:
      isSendMsg: true
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: false
        title: "groupCancelMuted title"
        desc: "groupCancelMuted desc"
        ext: "groupCancelMuted ext"
      defaultTips:
        tips: "group Cancel Muted"


    groupMemberMuted:
      isSendMsg: true
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: false
        title: "groupMemberMuted title"
        desc: "groupMemberMuted desc"
        ext: "groupMemberMuted ext"

    groupMemberCancelMuted:
      isSendMsg: true
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: false
        title: "groupMemberCancelMuted title"
        desc: "groupMemberCancelMuted desc"
        ext: "groupMemberCancelMuted ext"

    groupMemberInfoSet:
      isSendMsg: false
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: false
        title: "groupMemberInfoSet title"
        desc: "groupMemberInfoSet desc"
        ext: "groupMemberInfoSet ext"

    groupInfoSetAnnouncement:
      isSendMsg: true
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: false
        title: "groupInfoSetAnnouncement title"
        desc: "groupInfoSetAnnouncement desc"
        ext: "groupInfoSetAnnouncement ext"


    groupInfoSetName:
      isSendMsg: true
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: false
        title: "groupInfoSetName title"
        desc: "groupInfoSetName desc"
        ext: "groupInfoSetName ext"


    #############################friend#################################
    friendApplicationAdded:
      isSendMsg: false
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: false
        title: "Somebody applies to add you as a friend"
        desc: "Somebody applies to add you as a friend"
        ext: "Somebody applies to add you as a friend"

    friendApplicationApproved:
      isSendMsg: true
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: true
        title: "Someone applies to add your friend application"
        desc: "Someone applies to add your friend application"
        ext: "Someone applies to add your friend application"

    friendApplicationRejected:
      isSendMsg: false
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: true
        title: "Someone rejected your friend application"
        desc: "Someone rejected your friend application"
        ext: "Someone rejected your friend application"

    friendAdded:
      isSendMsg: false
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: true
        title: "We have become friends"
        desc: "We have become friends"
        ext: "We have become friends"

    friendDeleted:
      isSendMsg: false
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: true
        title: "deleted a friend"
        desc: "deleted a friend"
        ext: "deleted a friend"

    friendRemarkSet:
      isSendMsg: false
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: true
        title: "Your friend's profile has been changed"
        desc: "Your friend's profile has been changed"
        ext: "Your friend's profile has been changed"

    blackAdded:
      isSendMsg: false
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: true
        title: "blocked a user"
        desc: "blocked a user"
        ext: "blocked a user"

    blackDeleted:
      isSendMsg: false
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: true
        title: "Remove a blocked user"
        desc: "Remove a blocked user"
        ext: "Remove a blocked user"

    friendInfoUpdated:
      isSendMsg: false
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: true
        title: "friend info updated"
        desc: "friend info updated"
        ext: "friend info updated"

    #####################user#########################
    userInfoUpdated:
      isSendMsg: false
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: true
        title: "Remove a blocked user"
        desc: "Remove a blocked user"
        ext: "Remove a blocked user"

    #####################conversation#########################
    conversationChanged:
      isSendMsg: false
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: true
        title: "conversation changed"
        desc: "conversation changed"
        ext: "conversation changed"

    conversationSetPrivate:
      isSendMsg: true
      reliabilityLevel: 1
      unreadCount: false
      offlinePush:
        enable: true
        title: "burn after reading"
        desc: "burn after reading"
        ext: "burn after reading"
