kind: Job
apiVersion: batch/v1
metadata:
  name: kafka-topic-{{ include "openIM.fullname" . }}
  labels:
    {{- include "openIM.labels" . | nindent 4 }}
    app: kafka-topic
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
        - name: kafka-topic-creator
          image: docker.io/bitnami/kafka:3.4.1-debian-11-r0
          env:
            - name: KAFKA_BOOTSTRAP_SERVER
              value: {{ index .Values.configmap.kafka.ws2mschat.addr 0 }}
          command:
            - /bin/bash
            - -c
            - |
              topics=("{{.Values.configmap.kafka.ws2mschat.topic}}" "{{.Values.configmap.kafka.msgtomongo.topic}}" "{{.Values.configmap.kafka.ms2pschat.topic}}" "{{.Values.configmap.kafka.msgtomodify.topic}}")
              for topic in "${topics[@]}"
              do
                  echo "create topic $topic"
                  /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server $KAFKA_BOOTSTRAP_SERVER --replication-factor 1 --partitions 12 --topic $topic
              done
      restartPolicy: Never
  backoffLimit: 4
