apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{include "openIM.msg_gateway" . }}-{{ include "openIM.fullname" . }}
  labels:
    {{- include "openIM.labels" . | nindent 4 }}
    app: {{include "openIM.msg_gateway" . }}
spec:
  hosts:
    - {{ include "openIM.gatewayDomain" . | trim}}
  gateways:
    - {{include "openIM.msg_gateway" . }}-{{ include "openIM.fullname" . }}
  http:
    - route:
        - destination:
            host: {{include "openIM.msg_gateway" . }}-{{ include "openIM.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.wsPort }}
