apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{include "openIM.api" . }}-{{ include "openIM.fullname" . }}
  labels:
    {{- include "openIM.labels" . | nindent 4 }}
    app: {{include "openIM.api" . }}
spec:
  hosts:
    - {{ include "openIM.apiURL" . | trim}}
  gateways:
    - {{include "openIM.api" . }}-{{ include "openIM.fullname" . }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{include "openIM.api" . }}-{{ include "openIM.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
