name: Release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Why trigger?"
        required: true
        type: string
  push:
    branches-ignore:
      - '**'
    tags:
      - '*'


jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.16.x

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Helm package
        run: |
          helm package  charts/openIM
