name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '*'


jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Prepare
        id: prepare
        run: |
          echo "tag_name=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
          echo "$tag_name"

      - name: Helm package
        run: |
          helm package  charts/openIM

  call_ci_workflow:
    uses: ./.github/workflows/pages.yml
